server:
  port: 8083

## database configurations
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_app_yt
    username: root
    password: root
#    hikari:
#      pool-name: HikariCP
#      max-lifetime: 1800000
#      validation-timeout: 1800000
#      idle-timeout: 600000
#      connection-timeout: 10000
#      maximum-pool-size: 5
#      leak-detection-threshold: 0
#      initialization-fail-timeout: -1

  #jpa and hibernate configurations
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true

  sql:
    init:
      mode: always


### jwt settings here
  security:
      oauth2:
        client:
          registration:
            google:
              client-id: ${GOOGLE_CLIENT_ID:51768911754-83u3lb28ue0mdva86c7c2lmdn53geqt6.apps.googleusercontent.com}
              client-secret: ${GOOGLE_CLIENT_SECRET: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}
              scope:
                - email
                - profile
                - openid
            github:
              client-id: ${GITHUB_CLIENT_ID:Ov23li0NfcgfQ0WHteKQ}
              client-secret: ${GITHUB_CLIENT_SECRET:6e0b9863c1e821b7adccfc8135b6cc291650db5b}
              scope:
                - user:email
                - read:user
          provider:
            github:
              authorization-uri: https://github.com/login/oauth/authorize?prompt=consent


security:
    jwt:
      secret: ${JWT_SECRET:mmo,F{4b2C-x7y+xMc#}am{sEBmf0{sSL?^ii#K=y(8gsKnh#qaab^|[W--hdoPZ>$eP*i([K&)jfo%,ovkZ=S}
      issuer: ${JWT_ISSUER:api.substring.com}
      acess-ttl-seconds: ${JWT_ACCESS_TTL_SECONDS:3600}
      refresh-ttl-seconds: ${JWT_REFERESH_TTL_SECONDS:86400}
      refresh-token-cookie-name: ${JWT_REFRESH_COOKIE_NAME:refreshToken}
      cookie-secure: ${JWT_COOKIE_SECURE:true}
      cookie-http-only: ${JWT_COOKIE_HTTP_ONLY:true}
      cookie-same-site: ${JWT_COOKIE_SAME_SITE:lax}
      cookie-domain: ${JWT_COOKIE_DOMAIN:localhost}
