package com.substring.authapp.services;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.mail.MailException;
import org.springframework.mail.SimpleMailMessage;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.scheduling.annotation.Async;
import org.springframework.stereotype.Service;

/**
 * <h1>Outbound Communication Service</h1>
 * 
 * <p>Dedicated to handling all outbound email communications. This service acts as the 
 * final point of contact between the security layer and the user's inbox.</p>
 * 
 * <p><b>Implementation Workflow:</b>
 * 1. <b>Assembly:</b> Constructs professional, standardized email templates for security events.
 * 2. <b>Offloading:</b> Utilizes the {@link Async} annotation to push the high-latency SMTP 
 *    handshake to a background thread pool.
 * 3. <b>Dispatch:</b> Communicates with the configured SMTP server via {@link JavaMailSender}.
 * </p>
 * 
 * <p><b>Behind the Scenes (Async Orchestration):</b>
 * This service is enabled for asynchronous execution. When a method is called, 
 * Spring's {@code TaskExecutor} (configured in {@link com.substring.authapp.AuthAppApplication}) 
 * picks up the request and executes it in a background thread pool. This is a critical 
 * <b>Short-Circuit</b> for the main HTTP thread, ensuring it is never blocked by external 
 * SMTP latency.</p>
 * 
 * <p><b>Design Rationale (The "Why"):</b>
 * Email dispatch is a high-latency I/O operation. Offloading this to a background thread 
 * ensures a responsive user experience. Additionally, catching and logging {@link MailException} 
 * within the service prevents background failures from crashing the primary transaction thread.
 * </p>
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class EmailService {

    // ===================================================================================
    // SECTION 1: Infrastructure & Configuration (Fields)
    // ===================================================================================

    private final JavaMailSender mailSender;

    @Value("${spring.mail.username}")
    private String fromAddress;

    // ===================================================================================
    // SECTION 2: Security Event Dispatchers (Public)
    // ===================================================================================

    /**
     * Dispatches a password reset OTP to the user's registered email address.
     * 
     * <p><b>Implementation Workflow:</b>
     * 1. Constructs a {@link SimpleMailMessage} with the provided OTP and 5-minute TTL.
     * 2. Sets the 'from' address using the secure property injected via {@code @Value}.
     * 3. Attempts to send the email via the configured SMTP host.
     * 4. Catches and logs any {@link MailException} to prevent background thread failure.
     * </p>
     * 
     * <p><b>Behind the Scenes:</b>
     * Utilizes the {@code mailSender} bean which is automatically configured by 
     * {@code spring-boot-starter-mail} based on properties in {@code application.yaml}.
     * </p>
     * 
     * @param toAddress The recipient's email address.
     * @param otp The one-time password generated by the system.
     */
    @Async
    public void sendPassWordResetOtp(String toAddress, String otp) {
        sendOtpEmail(toAddress, otp, "Password Reset Verification", "requested a password reset");
    }

    /**
     * Dispatches a signup verification OTP to the candidate's email address.
     * 
     * @param toAddress Candidate email.
     * @param otp The 6-digit code.
     */
    @Async
    public void sendSignUpOtp(String toAddress, String otp) {
        sendOtpEmail(toAddress, otp, "Signup Verification", "initiated a new account registration");
    }

    // ===================================================================================
    // SECTION 3: Communication Engine (Internal)
    // ===================================================================================

    /**
     * Internal generic engine for dispatching professional OTP emails.
     */
    private void sendOtpEmail(String toAddress, String otp, String subject, String actionDescription) {
        try {
            log.info("Attempting to dispatch {} email to: {}", subject, toAddress);

            SimpleMailMessage message = new SimpleMailMessage();
            message.setTo(toAddress);
            message.setFrom(fromAddress);
            message.setSubject(subject);

            String content = String.format(
                "Hello,\n\n" +
                "You have %s. Please use the following One-Time Password (OTP) to verify your identity:\n\n" +
                "Verification Code: %s\n\n" +
                "This code is valid for exactly 5 minutes. If you did not initiate this request, " +
                "please ignore this email or contact support if you have concerns.\n\n" +
                "Thank you,\n" +
                "The Auth-App Security Team", 
                actionDescription, otp
            );

            message.setText(content);
            mailSender.send(message);

            log.info("Successfully dispatched {} email to: {}", subject, toAddress);
        } catch (MailException e) {
            log.error("Failed to send {} email to {}: {}", subject, toAddress, e.getMessage());
        }
    }
}
