package com.substring.authapp.repositories;

import com.substring.authapp.entities.Role;
import com.substring.authapp.entities.UserRole;
import org.springframework.data.jpa.repository.JpaRepository;

import java.util.Optional;
import java.util.UUID;

/**
 * <h1>Authorization Authority Data Access Provider</h1>
 *
 * <p>Data Access Object (DAO) for managing {@link Role} entities. This repository 
 * serves as the source of truth for the application's RBAC (Role-Based Access Control) 
 * system, providing the necessary persistence logic to hydrate security authorities.</p>
 *
 * <p><b>Implementation Workflow:</b>
 * 1. <b>Discovery:</b> Locates role definitions by their type-safe name.
 * 2. <b>Association:</b> Provides managed entities for user privilege assignment.
 * 3. <b>Handshake:</b> Managed by the <b>Persistence Context</b> during security principal hydration.
 * 4. <b>Proxying:</b> Generated by Spring Data JPA at startup using JDK Dynamic Proxies.
 * </p>
 *
 * <p><b>Behind the Scenes (Component Interaction):</b>
 * This repository leverages <b>Spring Data JPA Proxy Generation</b> to abstract 
 * complex JPQL queries. At runtime, the {@code findByName} method is intercepted 
 * by a proxy that executes an <b>Index-Driven Lookup</b> on the {@code role_name} 
 * column. This ensures that authority resolution is lightning-fast during the 
 * critical authentication filter phase.</p>
 *
 * <p><b>Design Rationale (The "Why"):</b>
 * By isolating role persistence, we decouple the application's authorization 
 * structure from the user management logic. The <b>Spring Data Proxy</b> 
 * ensures that role lookups are efficiently managed within the current 
 * <b>Persistence Context</b>, preventing redundant database hits for frequently 
 * accessed authority records.
 * </p>
 * 
 * @see com.substring.authapp.entities.Role
 * @see com.substring.authapp.entities.UserRole
 */
public interface RoleRepository extends JpaRepository<Role, UUID> {
    
    // ===================================================================================
    // SECTION 1: Authority Discovery
    // ===================================================================================

    /**
     * Finds a role by its unique {@link UserRole} enum.
     * 
     * <p><b>Implementation Workflow:</b>
     * Spring Data JPA parses the method name to generate a {@code SELECT r FROM Role r WHERE r.name = :name} 
     * query. This method is typically invoked during the registration flow or when 
     * promoting a user's privileges.
     * </p>
     *
     * @param name The type-safe name of the role (e.g., UserRole.ROLE_USER).
     * @return An {@link Optional} containing the role if it exists in the database.
     */
    Optional<Role> findByName(UserRole name);
}
