package com.substring.authapp.dtos.common;

import java.io.Serializable;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;

/**
 * <h1>Global API Error Structure</h1>
 * 
 * <p>A standardized, immutable response payload used across the entire application 
 * to provide predictable failure signaling to API consumers. It abstracts away 
 * internal exception details while providing actionable error metadata.</p>
 * 
 * <p><b>Implementation Workflow:</b>
 * 1. <b>Interception:</b> Custom exceptions are caught by the global handler.
 * 2. <b>Transformation:</b> Exception data is mapped to this immutable DTO.
 * 3. <b>Delivery:</b> Serialized as a JSON response with the appropriate HTTP status.
 * </p>
 * 
 * <p><b>Behind the Scenes (Exception Mapping):</b>
 * Instances of this record are generated by the {@link com.substring.authapp.exceptions.GlobalExceptionHandler}. 
 * When a controller or filter throws an exception, the handler extracts the 
 * relevant HTTP status and message, packaging them into this DTO for serialization.</p>
 * 
 * <p><b>Design Rationale (The "Why"):</b>
 * This DTO is a critical <b>Security Decoupling</b> layer. By strictly 
 * defining the fields returned to the client, we ensure that internal 
 * stack traces, database schema names, or sensitive server paths are never 
 * exposed in production. It <b>Decouples</b> the client's error handling 
 * from the server's internal exception hierarchy, providing a stable 
 * and safe contract for error reporting.</p>
 * 
 * @param status The HTTP status code (e.g., 401, 403, 404).
 * @param error The brief error category name.
 * @param message The user-friendly, localized error description.
 * @param path The URI path where the error occurred.
 * @param timestamp The UTC moment the error was captured.
 */
public record ApiError(
        // ===================================================================================
        // SECTION 1: Error Context (Fields)
        // ===================================================================================

        int status, 
        String error, 
        String message, 
        String path, 
        OffsetDateTime timestamp
) implements Serializable {

    // ===================================================================================
    // SECTION 2: Domain Helpers (Static Factories)
    // ===================================================================================

    public static ApiError of(int status, String error, String message, String path) {
        return new ApiError(status, error, message, path, OffsetDateTime.now(ZoneOffset.UTC));
    }
}
